apiVersion: v1
entries:
  sistatistics:
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2025-11-26T10:35:08.835354+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: a5d7f3d43285c59c0b2deadee9567bc7a8bf19e486630b7c6085a4dc2074f820
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2025-11-26T10:35:08.8348331+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: ff4f7357cd0bfcca182063ff5c7f1a3b031fb73d065360d806b62f800674ef4e
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2025-11-26T10:35:08.8210045+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: 803435cc540148009d80be0a2b80bebb3bec3ec222fff309f71a22b8e7a7520f
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2025-11-26T10:35:08.8087433+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: f817265d262c6d766c33ed736d1c48c7cea46f0d827ec95deff40fd4e2feb9d6
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.6
    created: "2025-11-26T10:35:08.783392+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: a9c99b70851a385a4d30d7b4ed805bb7393548fd7fc0fd33cd407a5cf5a55769
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v2
    appVersion: 1.0.5
    created: "2025-11-26T10:35:08.7699117+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: 7380d77c19c809cf117a9fbd287b88bd792351f2417b5d9d19a64b8b11e21f8d
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v2
    appVersion: 1.0.4
    created: "2025-11-26T10:35:08.7563239+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: 2bba49852b803a772b9c4ca89a30250d005a7935b1f6573d023d9622a849c28f
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v2
    appVersion: 1.0.3
    created: "2025-11-26T10:35:08.7443181+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: d21f039a603b44bd1e21ac43ddf477223039c17b8631fc8696c75af0d25a936e
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v2
    appVersion: 1.0.2
    created: "2025-11-26T10:35:08.7318274+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: 8087ae306d947071028cd7bc0b61ed8a55f753a5448443c034a3f36913352792
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2025-11-26T10:35:08.7158571+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: 22db702c2060f6f6e3c2bbd9a1c630c56f2f088e19a20206b6d52f70bd2d8f28
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-26T10:35:08.704356+01:00"
    description: Service for collecting SIGame games and packages statistics
    digest: 4a2f0621a249f19fc968bce8ef7a0334c64ac508ee63442710aae0be0b291fd1
    name: sistatistics
    type: application
    urls:
    - sistatistics-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-26T10:35:08.6906033+01:00"
